export enum FaIcons {
  $add = 'fas fa-plus',
  $delete = 'fas fa-trash-alt',
  $sliders = 'fas fa-sliders-h',
  $edit = 'fas fa-pen',
  $menu = 'fas fa-bars',
  $chevronDown = 'fas fa-chevron-down',
  $caretDown = 'fas fa-caret-down',
  $radioOn = 'far fa-dot-circle',
  $radioOff = 'far fa-circle',
  $box = 'far fa-square',
  $checkbox = 'far fa-check-square',
  $arrowRight = 'fas fa-chevron-right',
  $arrowLeft = 'fas fa-chevron-left',
  $arrowUp = 'fas fa-arrow-up',
  $filter = 'fas fa-align-justify',
  $marker = 'fas fa-map-marker-alt',
  $search = 'fas fa-search',
  $close = 'fas fa-times',
  $paperclip = 'fas fa-paperclip'
}

export enum MaterialIcons {
  $add = 'add',
  $delete = 'delete_forever',
  $chevronDown = 'expand_more',
  $group = 'expand_more',
  $caretDown = 'arrow_drop_down',
  $box = 'check_box',
  $checkbox = 'check_box_outline_blank',
  $arrowRight = 'chevron_right',
  $arrowLeft = 'chevron_left',
  $arrowUp = 'arrow_upward',
  $filter = 'filter_list',
  $search = 'search',
  $close = 'clear',
}
