import { defineAsyncComponent } from 'vue'
// @ts-ignore
import paths from './paths.json'

export const VApp = defineAsyncComponent(() => import(/*Vueland_component*/`${ paths['VApp'] }`))
export const VButton = defineAsyncComponent(() => import(/*Vueland_component*/`${ paths['VButton'] }`))
export const VBadge = defineAsyncComponent(() => import(/*Vueland_component*/`${ paths['VBadge'] }`))
export const VChip = defineAsyncComponent(() => import(/*Vueland_component*/`${ paths['VChip'] }`))
export const VCheckbox = defineAsyncComponent(() => import(/*Vueland_component*/`${ paths['VCheckbox'] }`))
export const VOverlay = defineAsyncComponent(() => import(/*Vueland_component*/`${ paths['VOverlay'] }`))
export const VModal = defineAsyncComponent(() => import(/*Vueland_component*/`${ paths['VModal'] }`))
export const VMenu = defineAsyncComponent(() => import(/*Vueland_component*/`${ paths['VMenu'] }`))
export const VTextField = defineAsyncComponent(() => import(/*Vueland_component*/`${ paths['VTextField'] }`))
export const VInput = defineAsyncComponent(() => import(/*Vueland_component*/`${ paths['VInput'] }`))
export const VFileInput = defineAsyncComponent(() => import(/*Vueland_component*/`${ paths['VFileInput'] }`))
export const VSelect = defineAsyncComponent(() => import(/*Vueland_component*/`${ paths['VSelect'] }`))
export const VForm = defineAsyncComponent(() => import(/*Vueland_component*/`${ paths['VForm'] }`))
export const VLabel = defineAsyncComponent(() => import(/*Vueland_component*/`${ paths['VLabel'] }`))
export const VGroup = defineAsyncComponent(() => import(/*Vueland_component*/`${ paths['VGroup'] }`))
export const VResize = defineAsyncComponent(() => import(/*Vueland_component*/`${ paths['VResize'] }`))
export const VIcon = defineAsyncComponent(() => import(/*Vueland_component*/`${ paths['VIcon'] }`))
export const VTooltip = defineAsyncComponent(() => import(/*Vueland_component*/`${ paths['VTooltip'] }`))
export const VNavigation = defineAsyncComponent(() => import(/*Vueland_component*/`${ paths['VNavigation'] }`))
export const VMain = defineAsyncComponent(() => import(/*Vueland_component*/`${ paths['VMain'] }`))
export const VTextarea = defineAsyncComponent(() => import(/*Vueland_component*/`${ paths['VTextarea'] }`))
export const VSkeleton = defineAsyncComponent(() => import(/*Vueland_component*/`${ paths['VSkeleton'] }`))
export const VDataTable = defineAsyncComponent(() => import(/*Vueland_component*/`${ paths['VDataTable'] }`))
export const VDatePicker = defineAsyncComponent(() => import(/*Vueland_component*/`${ paths['VDatePicker'] }`))
export const VAutocomplete = defineAsyncComponent(() => import(/*Vueland_component*/`${ paths['VAutocomplete'] }`))
export const VProgressLinear = defineAsyncComponent(() => import(/*Vueland_component*/`${ paths['VProgressLinear'] }`))
export const VProgressCircular = defineAsyncComponent(() => import(/*Vueland_component*/`${ paths['VProgressCircular'] }`))
export const VCard = defineAsyncComponent(() => import(/*Vueland_component*/`${ paths['VCard'] }`))
export const VCardTitle = defineAsyncComponent(() => import(/*Vueland_component*/`${ paths['VCardTitle'] }`))
export const VCardSubtitle = defineAsyncComponent(() => import(/*Vueland_component*/`${ paths['VCardSubtitle'] }`))
export const VCardContent= defineAsyncComponent(() => import(/*Vueland_component*/`${ paths['VCardContent'] }`))
export const VCardActions= defineAsyncComponent(() => import(/*Vueland_component*/`${ paths['VCardActions'] }`))
export const VToolbar = defineAsyncComponent(() => import(/*Vueland_component*/`${ paths['VToolbar'] }`))
export const VToolbarContent = defineAsyncComponent(() => import(/*Vueland_component*/`${ paths['VToolbarContent'] }`))
export const VToolbarItems = defineAsyncComponent(() => import(/*Vueland_component*/`${ paths['VToolbarItems'] }`))
export const VToolbarLogo = defineAsyncComponent(() => import(/*Vueland_component*/`${ paths['VToolbarLogo'] }`))
export const VToolbarNavBtn = defineAsyncComponent(() => import(/*Vueland_component*/`${ paths['VToolbarNavBtn'] }`))
export const VList = defineAsyncComponent(() => import(/*Vueland_component*/`${ paths['VList'] }`))
export const VListItem = defineAsyncComponent(() => import(/*Vueland_component*/`${ paths['VListItem'] }`))
export const VListItemTitle = defineAsyncComponent(() => import(/*Vueland_component*/`${ paths['VListItemTitle'] }`))
export const VListItemSubtitle = defineAsyncComponent(() => import(/*Vueland_component*/`${ paths['VListItemSubtitle'] }`))
export const VListItemContent = defineAsyncComponent(() => import(/*Vueland_component*/`${ paths['VListItemContent'] }`))
export const VListItemIcon = defineAsyncComponent(() => import(/*Vueland_component*/`${ paths['VListItemIcon'] }`))
export const VLayout = defineAsyncComponent(() => import(/*Vueland_component*/`${ paths['VLayout'] }`))
export const VRow = defineAsyncComponent(() => import(/*Vueland_component*/`${ paths['VRow'] }`))
export const VCol = defineAsyncComponent(() => import(/*Vueland_component*/`${ paths['VCol'] }`))
export const VSpacer = defineAsyncComponent(() => import(/*Vueland_component*/`${ paths['VSpacer'] }`))
