# Github CI/CD
# config actions file
# -------------------
# Copyright (c) by Anar Allahverdiev
# ----------------------------------
name: CI
on:
  push:
    branches:
      - master
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Testing start
        run : echo "Hello first test"


  deploying:
    runs-on: ubuntu-latest
    steps:
      - name: Testing start
        run : echo "Hello first deploy"