# Github CI/CD
# config actions file
# -------------------
# Copyright (c) by Anar Allahverdiev
# ----------------------------------
name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - develop

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js 15
        uses: actions/setup-node@v1
        with:
          node-version: "15"
      - run: npm install
      - run: sudo npm i -g shelljs

  build:
    needs: [install]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npm run build:all --if-present
